### ISSUE TITLE
Title "Mx" not recognised, parsed as first name

### ISSUE THREAD

**Issue by nickynicolson** [derek73/python-nameparser#114]
The "Mx" title (https://en.wikipedia.org/wiki/Mx_(title)) is not recognised, it is instead parsed as a first name. Example below:

```{python}
In [1]: from nameparser import HumanName

In [2]: HumanName('Ms A.J. Smith')
Out[2]: 
<HumanName : [
        title: 'Ms'
        first: 'A.J.'
        middle: ''
        last: 'Smith'
        suffix: ''
        nickname: ''
]>

In [3]: HumanName('Mx A.J. Smith')
Out[3]: 
<HumanName : [
        title: ''
        first: 'Mx'
        middle: 'A.J.'
        last: 'Smith'
        suffix: ''
        nickname: ''
]>
```

**Comment by ybressler** [comment]
I've noticed the same issue with `Mz.` --> I'm going to create a separate issue for it.

**Comment by evrial** [comment]
You can add to constants and the titles in the nonbinary universe

**Comment by nickynicolson** [comment]
@evrial its perfectly reasonable to request that this is implemented in the package itself, rather than as a local modification, as detailed here https://github.com/derek73/python-nameparser#contributing
