### ISSUE TITLE
Baroness is not recognised as a title

### ISSUE THREAD

**Issue by gwire** [derek73/python-nameparser#117]
`baron` is listed in titles.py, but `baroness` is not. 

**Baroness** is a title used in the [House of Lords](https://members.parliament.uk/members/Lords?SearchText=baroness&PartyId=&Gender=Any&MembershipStatus=0&PolicyInterestId=&Experience=&ShowAdvanced=False).

**Comment by Yeboahmedia** [comment]
You can add this to your code using the configuration constants or instances.
[See customisation documentation](https://nameparser.readthedocs.io/en/latest/customize.html)

```
from nameparser.config import CONSTANTS
CONSTANTS.titles.add('baroness')
```
