### ISSUE TITLE
Duke as a first name not a title

### ISSUE THREAD

**Issue by cas--** [derek73/python-nameparser#125]
We recently had a new user sign-up and their first name _Duke_ kept disappearing which was identified as a result of parsing the name since Duke was being marked a title. 

I have applied the _constants_ workaround for now but it seems that Duke as a first name is becoming more common these days and perhaps this package could consider a fix for this. One thought is that, unless I am mistaken, the title Duke is always followed by 'of' e.g. 'Duke of Edinburgh' so could this be used to distinguish between first name and title?

An example of a famous "first name" Duke was the jazz composer [Duke Ellington](https://en.wikipedia.org/wiki/Duke_Ellington), although it was a nickname it is still not a title here. 

```
>>> from nameparser import HumanName
>>> HumanName("Duke Ellington")
<HumanName : [
	title: 'Duke' 
	first: '' 
	middle: '' 
	last: 'Ellington' 
	suffix: ''
	nickname: ''
]>
```

I can workaround the issue as explained in the documentation:
```
>>> from nameparser.config import CONSTANTS
>>> CONSTANTS.titles.remove('Duke')
>>> HumanName("Duke Ellington")
<HumanName : [
	title: '' 
	first: 'Duke' 
	middle: '' 
	last: 'Ellington' 
	suffix: ''
	nickname: ''
]>
```

**Comment by derek73** [comment]
That sounds reasonable. 

Anyone that would like "duke" to be parsed as a title can use:

```
>>> from nameparser.config import CONSTANTS
>>> CONSTANTS.titles.add('Duke')
```
