### ISSUE TITLE
Wrong parsing of 3 word name starting with prefix

### ISSUE THREAD

**Issue by curita** [derek73/python-nameparser#126]
Parsing the name "Van Maximilian Carlson" fails to recognize any part as last name.

```
$ python tests.py "Van Maximilian Carlson"
<HumanName : [
	title: ''
	first: 'Van Maximilian Carlson'
	middle: ''
	last: ''
	suffix: ''
	nickname: ''
]>
```

I think I would expect this case to be treated like when there's two words, the first starting with a prefix, when the prefix is considered the first name, something like:
```
<HumanName : [
	title: ''
	first: 'Van'
	middle: 'Maximilian'
	last: 'Carlson'
	suffix: ''
	nickname: ''
]>
```

But it might be something related to that specific prefix, as "Van" can often be a name.

I fixed locally by removing "van" from the prefixes config list, but I wanted to raise this issue in case it's worth it to address in the project.

**Comment by derek73** [comment]
Thanks for the raising the issue. I didn't realize Van could be a first name too. We should remove it from the constants list.
