### ISSUE TITLE
Is it possible to change the database instead of adding conjuctions? - (There is not enough data in the US Census Compared to WGND)

### ISSUE THREAD

**Issue by JayadityaSha** [derek73/python-nameparser#134]
I noticed the ability to add conjunctions that allows adding some names, suffixes etc but is it possible to select a different database for the F Names and L Names? I noticed the parser module uses US Census data, which is hardly inclusive of many names worldwide so I would for my case want to use WGND 2.0 ( World Gender Name Database 2.0) which has about 12.6 million records. 

Thank you very much for your efforts in developing this module, and if it is possible to change the database please let me know.

**Comment by derek73** [comment]
- Derek 📱

**Comment by derek73** [comment]
The parser does not use a database of first or last names. First and last names are determined only by position in the string. The only datasets included with the parser are for other common name parts like titles and suffixes. You can customize these datasets for your individual use case as mentioned in the documentation, but there are no prebuilt configurations other than the default.
