### ISSUE TITLE
Hangs in _order_name if a single all uppercase name is submitted

### ISSUE THREAD

**Issue by nrshapiro** [derek73/python-nameparser#142]
On a form where users enter names, among other things, I call:

    names = HumanNames(names_mess)

A user entered the uppercase acronym EMDR (since it searches names among other things) and it ended up generating a 500 error.

and with names_mess="EMDR"  it loops infinitely in:

def _order_name(tokens):
        ...
        new_tokens = deque(tokens)
        while new_tokens[-1].type == "INITIAL":
            token = new_tokens.pop()
            new_tokens.appendleft(token)
        return new_tokens

because there's only one token and it's of type INITIAL, so there's no end condition. 

This loop should never be entered with only one token in new_tokens to avoid an infinite loop.

**Comment by derek73** [comment]
@nrshapiro the nameparser is handles "EMDR" without failing. That infinite loop is not in this project's code.

```
% python tests.py "EMDR"
<HumanName : [
	title: '' 
	first: 'EMDR' 
	middle: '' 
	last: '' 
	suffix: ''
	nickname: ''
]>
```

**Comment by nrshapiro** [comment]
Sorry, I reported by searching for namesparser on Github when I did that I only saw yours.  The bug is in https://github.com/gwu-libraries/namesparser/blob/master/namesparser.py
