### ISSUE TITLE
Ph.D., Esq., M.D., C.F.P., etc. are titles, not suffixes

### ISSUE THREAD

**Issue by derek73** [derek73/python-nameparser#2]
Moving [the previous issue](https://code.google.com/p/python-nameparser/issues/detail?id=7) from the Google Code because I like the idea and would like to implement it, someday. Originally posted by jayqhacker, Feb 7, 2012.

----
Ph.D., Esq., M.D. and other titles are classified as suffixes.  This is perhaps convenient for parsing, since they appear at the end of a name, but they are in fact titles.  A suffix distinguishes people and is part of your legal name; a title does not and (in most countries) is not.  "J. Smith Jr." and "J. Smith Sr." are certainly different people, whereas "J. Smith", "J. Smith, PhD" and "J. Smith, MD" may or may not be.

I propose titles end up in the .title field, and suffices end up in the .suffix field.

Name parsing is a hard problem; ultimately I think you'd want a statistical, machine learning approach, but you can probably get pretty far with rules.

The two issues are: 1) some suffixes are part of your name, some aren't; and 2) some titles come before your name, some after. 

You could solve both by splitting titles into pre- and post-titles, and making suffixes just `('jr','sr','2','i','ii','iii','iv','v')`.

-----

Project Member #3 derek73

I played with adding a new list to keep track of titles that were added at the end. If we treat the suffixes as a definitive and complete list, then we can assume anything else is a title. The initials "i" and "v" are problematic, but we could probably assume that they are initials in the case of "John V". 

I like the idea of separating out the parts of the name that definitely signify another person, and your definition of suffix. Thinking about it, I guess a suffix always comes directly after the name? Like you wouldn't have "John Doe, Phd, Jr". Also the case of having 2 suffixes seems somewhat remote, e.g. "'Smith, John E, III, Jr'"? So I guess that would make the patterns look something like this.

```
# no commas:      title first middle middle middle last suffix|title_suffix title_suffix
# suffix comma:   title first middle last, suffix|title_suffix [, title_suffix]
# lastname comma: last, title first middles[,] suffix|title_suffix [,title_suffix]

SUFFIXES = set((
    'jr','sr','2','i','ii','iii','iv','v',
))

TITLE_SUFFIXES = set((
    'phd','md','esquire','esq','clu','chfc','cfp',
))
```
I got as far as finding that equality test would need to be updated. It got me wondering if perhaps we should change the equality test, per your example, to test that ' '.join(first, middle, last, suffix) are the same. Perhaps its easy enough for someone to test if unicode() representations are equal on their own if they want titles too. Or maybe that's too smart.

----

That sounds like a reasonable approach.  I don't personally use equality, but you might consider having it do the "dumb" least-surprise exact comparison, and adding a similarity method that returns a float in 0.0 - 1.0, eventually aiming for something like the probability that these two names reference the same person.

Also, watch out for "King John V."  ;)

**Comment by belisariussmith** [comment]
Technically they are not titles either. They are in fact **post-nominals**. Titles would be: _Dr, Sir, Rev, Mr_. However, suffixes are indeed _Jr, Sr, III_, etc.
