### ISSUE TITLE
First name Van (which is also sometimes a prefix) not handled correctly

### ISSUE THREAD

**Issue by htoothrot** [derek73/python-nameparser#24]
```python
>>> from nameparser import HumanName
... HumanName('Van Nguyen')
0: <HumanName : [
	title: '' 
	first: 'Van Nguyen' 
	middle: '' 
	last: '' 
	suffix: ''
	nickname: ''
]>
>>> import nameparser
>>> nameparser.VERSION
1: (0, 3, 3)
>>>
```

**Comment by jonathanmorgan** [comment]
Any idea when this will make it into a release?  I am running into this particular problem as well, trying to figure out what default behavior for "two word names with first word that could be first name or prefix" I should plan for.

Thanks!

Jon Morgan

**Comment by jonathanmorgan** [comment]
Thank you very much!  If there is ever anything I can do to help with this project, let me know.  I work with news content, and having a concrete, standardized way of parsing names, then using the parsed result to generate full name strings has been a substantial help.
