### ISSUE TITLE
Last Name 'Ma' treated as a suffix

### ISSUE THREAD

**Issue by lebailly** [derek73/python-nameparser#26]
```{python}
In [1]: HumanName('Andrew Ma')
Out[1]: 
<HumanName : [
	title: '' 
	first: 'Andrew' 
	middle: '' 
	last: 'Ma' 
	suffix: ''
	nickname: ''
]>

In [2]: HumanName('Ma, Andrew')
Out[2]: 
<HumanName : [
	title: '' 
	first: 'Andrew' 
	middle: '' 
	last: '' 
	suffix: 'Ma'
	nickname: ''
]>
```

In line 1 the name is correctly parsed.  However in line 2 (when it is listed "last name, first") the Ma is treated as a suffix and there is no last name.  In my opinion, since there is no last name the parser should assume it's a last name and not a suffix.

**Comment by derek73** [comment]
I agree, this feels like a bug. All of the comma variations should work the same. Probably missing a test someplace and not too hard a fix.
