### ISSUE TITLE
'Co-Chairs' is not detecting as formal title

### ISSUE THREAD

**Issue by sayandev** [derek73/python-nameparser#37]
name = HumanName('Co-Chairs Muffy Miller')
name.first+' '+name.last
u'Co-Chairs Miller'

**Comment by derek73** [comment]
We can add co-chairs to the titles constant. In the meantime you can also add that in your own project.  See the documentation section on customizing the parser.

**Comment by sayandev** [comment]
Thanks a lot Derek.
