### ISSUE TITLE
Middle initial 'e.' remains lowercase when using capitalize()

### ISSUE THREAD

**Issue by scottwernervt** [derek73/python-nameparser#39]
Middle initial `e.` will remain lower case after calling `capitalize()`. I am using Python3.4 and nameparser-0.3.10

    >>> name = HumanName('scott e. werner')
    >>> name
    <HumanName : [
        title: '' 
        first: 'scott' 
        middle: 'e.' 
        last: 'werner' 
        suffix: ''
        nickname: ''
    ]>
    >>> name.capitalize()
    >>> name
    <HumanName : [
        title: '' 
        first: 'Scott' 
        middle: 'e.' 
        last: 'Werner' 
        suffix: ''
        nickname: ''
    ]>

I cannot repeat the bug with the middle initial: `l.`

    >>> name = HumanName('scott l. werner')
    >>> name.capitalize()
    >>> name
    <HumanName : [
        title: '' 
        first: 'Scott' 
        middle: 'L.' 
        last: 'Werner' 
        suffix: ''
        nickname: ''
    ]>

**Comment by derek73** [comment]
Thanks for the bug report! Should be fixed in v0.3.11
