### ISSUE TITLE
HumanName("Royce, Ed") treats Ed as a suffix

### ISSUE THREAD

**Issue by doveIn** [derek73/python-nameparser#42]
HumanName("Ed, Royce") treats "Ed" as a suffix and gives no last name. Ed is a very common first name. For instance, Ed Royce is a current congressman from California. Not sure if that should be in the default suffix list for this reason.

**Comment by derek73** [comment]
That sounds like a bug, probably introduced in version v0.3.9 where I changed the handling of suffixes. Thanks for reporting it.
