### ISSUE TITLE
document that to effectively add to suffixes you have to add to suffix_acronyms

### ISSUE THREAD

**Issue by gvelez17** [derek73/python-nameparser#49]
So it took me a long time to understand why

nameparser.config.CONSTANTS.suffixes.add('pc') 

was not effective, finally realized by reading the code that

nameparser.config.CONSTANTS.suffix_acronyms.add('pc') 

would be, but it was not obvious.  Maybe add this to the docs.

**Comment by derek73** [comment]
I've been burnt by this myself. When I originally split suffixes up in to different types I didn't even realize that `CONSTANTS.suffixes` is no longer hooked up to anything. I removed the documentation for [`suffixes`](http://nameparser.readthedocs.io/en/latest/customize.html#editable-attributes-of-nameparser-config-constants) but I think I need to just remove it entirely.
