### ISSUE TITLE
JOHN DOE M.D. incorrect suffix

### ISSUE THREAD

**Issue by ipartola** [derek73/python-nameparser#55]
This ends up being capitalized to:

`<HumanName : [
	title: ''
	first: 'John'
	middle: ''
	last: 'Doe'
	suffix: 'M.d.'
	nickname: ''
]>`

Note that "M.d." should be "M.D.". Curiously, JOHN DOE MD works fine.

**Comment by derek73** [comment]
Didn't notice this before but this is actually by design. The parser doesn't change the capitalization of mixed-case strings unless you for it to, e.g. `name.capitalize(force=True)`.

http://nameparser.readthedocs.io/en/latest/usage.html#capitalization-support
