### ISSUE TITLE
Last names that begin with Mac don't capitalize properly

### ISSUE THREAD

**Issue by ipartola** [derek73/python-nameparser#56]
The easy case of this is last names that are four letters long and contain Mac: MACK and MACE end up being capitalized to MacK and MacE.

The more complicated case would be names like MACBETH (should be Macbeth, not MacBeth) and MACARONI (should be Macaroni, not MacAroni). I think this should be solved with a whitelist of last names that should not have the letter after Mac capitalized.

The one that'll give ya a real headache is MACLEAN (could be either MacLean or Maclean).

**Comment by derek73** [comment]
This is the regex that is currently being used to match for "Mac" in the capitalization: 

`^(ma?c)(\w+)`

Here's where it's being used: 
https://github.com/derek73/python-nameparser/blob/master/nameparser/parser.py#L743

If you can find a regex that works better, I'd be happy to update it. You can test out your regex like this:

```python
from nameparser.config import CONSTANTS
CONSTANTS.regexes.add('mac', r'^(ma?c)(\w+)')
# instantiate new HumanName instance
```

**Comment by derek73** [comment]
`r'^(ma?c)(\w{2,})'` seems to work. requires 2 or more word characters after the "mac".
