### ISSUE TITLE
Emojis are parsed as valid names

### ISSUE THREAD

**Issue by edwardotis** [derek73/python-nameparser#58]
In latest release:
 "John  Doe ☁️" returns:
first: John
middle: Doe
last: ☁️
https://emojipedia.org/cloud/

Maybe somebody wants emojis for names, but it would be useful to have a config to remove emoji's.

**Comment by derek73** [comment]
This appears to be a way to remove emoji from a string:

https://stackoverflow.com/questions/26568722/remove-unicode-emoji-using-re-in-python

I implemented it as a regex in the existing config. By default it will remove emoji but you can disable it by setting the new 'emoji' regex to False. I also added some documentation: 

http://nameparser.readthedocs.io/en/latest/customize.html#don-t-remove-emojis

It would be nice if you could give it a try before I push an updated release to pypi:

`pip install -e git+git://github.com/derek73/python-nameparser.git#egg=nameparser`

Let me know if any problems or other ideas.

**Comment by edwardotis** [comment]
Confirmed working for the following test case on python 3.5.

Input:
John Doe 😀☁

Output:
first: John
middle: 
last:Doe

Thanks for the quick turnaround!
