### ISSUE TITLE
Can't install on Python 3

### ISSUE THREAD

**Issue by Angel-Gonzalez** [derek73/python-nameparser#6]
I got this error while i'm trying to install on my Python3 enviroment. I'm a novice on programming so if you may point it out what i'm doing wrong.
angel@angel-K72Jr:~/development/nameparser-0.2.7$ sudo python3.2 setup.py install
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    import nameparser
  File "/home/angel/development/nameparser-0.2.7/nameparser/**init**.py", line 8, in <module>
    from parser import HumanName
ImportError: cannot import name HumanName

**Comment by zakariaabedin** [comment]
from nameparser import HumanName
ImportError: cannot import name 'HumanName'

I get his error in Python 3.6. Please help me solve this. I am using the latest version of NameParser
