### ISSUE TITLE
possibly incorrect parsing of "grand"

### ISSUE THREAD

**Issue by thehesiod** [derek73/python-nameparser#63]
Just noticed that if I parse "Grand Rounds", it returns:
```python
>>> name
<HumanName : [
	title: 'Grand' 
	first: '' 
	middle: '' 
	last: 'Rounds' 
	suffix: ''
	nickname: ''
]>
```

Kinda odd no?

**Comment by derek73** [comment]
"Grand" is included as a title which means it will never be considered a first name. I'm guessing you expect it to be parsed as firstname lastname? Is that an actual person's name? I took a quick poke around in [the SSA baby names data](https://www.ssa.gov/oact/babynames/limits.html) and couldn't find "Grand" used as a first name. Maybe this name is more common in other countries?

Including "grand" in titles allows for matching of multiword titles that include it, e.g. "Grand Duke" or "Grand Duchess". Though, those [don't appear to be very common titles either](https://en.wikipedia.org/wiki/Title), so maybe we should just remove it from the titles constant.

**Comment by thehesiod** [comment]
These are all good questions. Personally I would have expect title + first name or first + last.  Title + last doesn't sound right.

**Comment by thehesiod** [comment]
This isn't a person's name BTW. I'm using this module to parse email address names and send it a email which came from "Grand Rounds" which is a company name.

**Comment by thehesiod** [comment]
Ex: Grand Duke Henri, looks like this is a known Duke and is his first name

**Comment by derek73** [comment]
It gets complicated. When followed by a single name part, there's actually a [set of titles](http://nameparser.readthedocs.io/en/latest/modules.html#module-nameparser.config.titles) which are followed by first names (Uncle Bob, Queen Mary) and a separate set followed by last names (Admiral Cartwright, Officer Johnson), the larger set is currently expecting last names to follow .

But that makes me think, actually there's actually a few things in that titles constant that should only be title parts if they are followed by another title part, meant to be chained together. For example "Grand" is only a title when it's followed by another title part, "duke" or "duchess" or a few others. But never in your case where it's not followed by another title.

**Comment by thehesiod** [comment]
Ya this is complicated :) I'm sure there are ambiguous cases too. Maybe need like probability for each word ;)
