### ISSUE TITLE
bad parsing

### ISSUE THREAD

**Issue by Miando** [derek73/python-nameparser#68]
full_name = 'Virginia G. Essandoh, J.D. '
output: first name = 'J.D.'

**Comment by Miando** [comment]
full_name = 'Wm. Scott Magargee III'
output: first name = 'Wm.'

**Comment by derek73** [comment]
thanks for the ticket. I added both of those in v0.5.5.

**Comment by Miando** [comment]
Thanks you, great tool!
Also I issue when middle name was in first place, like 'J. Smith Adam' 
output first name was "J."

Maybe its the same issue from my previous message, not sure

**Comment by derek73** [comment]
Thanks!

Yea I don't think that's something this parser can support. If it had a comma after Smith, it would work. The previous examples were 2-letter abbreviations that are not potential first names so we can match against those without messing up the first and last name behavior. I don't think there's any rule-based way to know that J. is a middle name in that example. I mean, without a comma it would probably trip up a lot of humans. :) I think you can only know if you know that "Adam" is not likely to be a last name. This library is just rules, nothing probabilistic yet.
