### ISSUE TITLE
Parsing title and last name, e.g. "Mr XXX" should be last name, not first name

### ISSUE THREAD

**Issue by danhartropp** [derek73/python-nameparser#7]
Love this library - very useful. 

However, I've noticed that parsing names in the format Prefix Lastname (e.g. Mr Magoo) parse with a blank name.last and the last name in the first name position (e.g. name.first == Magoo, name.last == ''). I think this should be the other way round!

I may have time to fix this in your code later, but for now i'm using the following kludge to make it work in my code...

if name.title != '':
        if name.last == '':
            name.last = name.first
            name.first = ''

**Comment by sayandev** [comment]
Hi Derek,

I was trying to use name-parser to get rid of formal titles such as Dr., Mayor, Co-Chairs

For the first two options i.e. Dr. & Mayor the code snippet is working fine:

name = HumanName('Mayor Michael Bloomberg')
name.first+' '+name.last

But for 'Co-Chairs' its not working as per expectation:
>>> name = HumanName('Co-Chairs Muffy Miller')
>>> name.first+' '+name.last
u'Co-Chairs Miller'

Just wondering can the 'Co-Chairs' in the definition of a title. A quick response will be highly appreciated.

Best,
Sayan
