### ISSUE TITLE
Parsing multi-name strings

### ISSUE THREAD

**Issue by Justasic** [derek73/python-nameparser#79]
I really wasn't sure how to word this but is there a way to parse names that are formatted as follows:
`Rob And Beth Edmunds`

to output as separate names like:
`["Rob Edmunds", "Beth Edmunds"]`

or does this have to be parsed separately?
Thanks!

**Comment by derek73** [comment]
There is no way to do this currently with the parser. I’d suggest doing some post processing to find names with “and” in the first name slot and then create two names.

**Comment by Justasic** [comment]
Yeah that was what I ended up doing in the end (along with the ampersand), I didn't see anything in the docs for this kind of scenario so I was unsure if there was a way to handle this.
