### ISSUE TITLE
Parsing a name with hyphen

### ISSUE THREAD

**Issue by catap** [derek73/python-nameparser#95]
Look like `HumanName` isn't compatibly with a name that contains hyphen.

As I understand in the world it is possibly to have a few different system of them.

For example an article at wikipedia: https://en.wikipedia.org/wiki/Double-barrelled_name

Any ideas of possibility to add it here?

**Comment by vaneseltine** [comment]
Could you give an example?

```
>>> HumanName('joe-bob bill-sue hyphenated-last-name')
<HumanName : [
	title: ''
	first: 'joe-bob'
	middle: 'bill-sue'
	last: 'hyphenated-last-name'
	suffix: ''
	nickname: ''
]>
```
